build-job:
  image: cirrusci/flutter:stable
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  artifacts:
    untracked: true
  script:
    - flutter build web

deploy-job:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  dependencies:
    - build-job
  script:
    - aws s3 sync build/web s3://rivia-frotnend.com
    - aws cloudfront create-invalidation --distribution-id E22LUVITD97BOO --paths '/*'