build-job:
  image: cirrusci/flutter:stable
  stage: build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  artifacts:
    untracked: true
  script:
    - flutter build web

test-job:
  image: cirrusci/flutter:stable
  stage: test
  script:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt -y -f install ./google-chrome-stable_current_amd64.deb
    - flutter pub get
    - flutter test --platform chrome

deploy-job:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  dependencies:
    - build-job
  script:
    - aws s3 sync build/web s3://rivia-frontend/
