enum Lang {
  en,
  ua,
}

enum LangText {
  langCode,
  loginAsAdmin,
  loginAsUser,
  rivia,
  aggregateStats,
  aggregateParticipants,
  detailedNeededRate,
  detailedPreparedRate,
  detailedPrepared,
  noOneNotNeeded,
  noOneNotPrepared,
  confidentialSurvey,
  presets,
  newPreset,
  bad,
  good,
  needed,
  prepared,
  all,
  yes,
  no,
  additionalComments,
  skip,
  next,
  submit,
  meetings,
  filters,
  dashboard,
  select,
  meetingName,
  participants,
  date,
  time,
  startTime,
  endTime,
  signUp,
  login,
  firstName,
  surname,
  email,
  password,
  analytics,
  organiser,
  noParticipants,
  lvlSat,
  neededParticipants,
  preparedParticipants,
  summary,
  overallSat,
  feedback,
  from,
  to,
  meetingSatisfactionBetween,
  and,
  selectColumns,
  largeMeetings,
  cancelMultiUser,
  multiSelect,
  showMultiSelectSummary,
  createNewMeeting,
  amazing,
  great,
  ok,
  bad2,
  inadequate,
  reset,
  preset,
  presetNum,
  generalQuality,
}

extension LangTextContent on LangText {
  static const langTexts = {
    LangText.langCode: ['EN', 'УК'],
    LangText.rivia: ['RIVIA', 'РІВІЯ'],
    LangText.loginAsAdmin: ['Login as admin', 'Увійти як адміністратор'],
    LangText.loginAsUser: ['Login as user', 'Увійти як користувач'],
    LangText.aggregateStats: ['Aggregate Stats', 'Зведена статистика'],
    LangText.aggregateParticipants: [
      'Number of participants',
      'Кількість учасників',
    ],
    LangText.detailedNeededRate: [
      'How needed a person was for a meeting',
      'Наскільки потрібна була людина для зустрічі',
    ],
    LangText.detailedPreparedRate: [
      'How prepared a person was for a meeting',
      'Наскільки підготовлена людина до зустрічі',
    ],
    LangText.noOneNotNeeded: [
      'No one voted as not needed',
      'Ніхто не голосував як непотрібний',
    ],
    LangText.noOneNotPrepared: [
      'No one voted as not prepared',
      'Ніхто не голосував як не підготовлений',
    ],
    LangText.confidentialSurvey: [
      'Confidential Survey',
      'Конфіденційне опитування',
    ],
    LangText.bad: ['BAD', 'ПОГАНО'],
    LangText.good: ['GOOD', 'ДОБРО'],
    LangText.needed: [
      'Is this participant needed?',
      'Чи потрібен цей учасник?',
    ],
    LangText.prepared: [
      'Is this participant prepared?',
      'Чи підготовлений цей учасник?',
    ],
    LangText.all: ['ALL', 'ВСІ'],
    LangText.yes: ['YES', 'ТАК'],
    LangText.no: ['NO', 'НІ'],
    LangText.additionalComments: ['Additional Feedback', 'Додатковий відгук'],
    LangText.skip: ['Skip', 'Пропустити'],
    LangText.next: ['Next', 'Далі'],
    LangText.submit: ['Submit', 'Подати'],
    LangText.meetings: ['Meetings', 'Зустрічі'],
    LangText.select: ['Select', 'Виберіть'],
    LangText.dashboard: ['Dashboard', 'Панель приладів'],
    LangText.meetingName: ['Meeting Name', 'Назва зустрічі'],
    LangText.participants: ['Participants', 'Учасники'],
    LangText.date: ['Date', 'Дата'],
    LangText.time: ['Time', 'Час'],
    LangText.startTime: ['Start Time', 'Час початку'],
    LangText.endTime: ['End Time', 'Час закінчення'],
    LangText.signUp: ['Sign Up', 'Зареєструватися'],
    LangText.login: ['Login', 'Увійти'],
    LangText.firstName: ['First Name', 'Ім\'я'],
    LangText.surname: ['Surname', 'Прізвище'],
    LangText.email: ['Email', 'Електронна пошта'],
    LangText.password: ['Password', 'Пароль'],
    LangText.analytics: ['Analytics', 'Аналітика'],
    LangText.organiser: ['Organiser', 'Організатор'],
    LangText.noParticipants: ['Number of Participants', 'Кількість учасників'],
    LangText.lvlSat: ['Level of Satisfaction', 'Рівень задоволеності'],
    LangText.neededParticipants: ['Needed Participants', 'Потрібні учасники'],
    LangText.preparedParticipants: [
      'Prepared Participants',
      'Підготовлені учасники',
    ],
    LangText.summary: ['Summary', 'Резюме'],
    LangText.overallSat: ['Overall Satisfaction', 'Загальне задоволення'],
    LangText.feedback: ['Feedback', 'Зворотній зв\'язок'],
    LangText.from: ['From', 'Від'],
    LangText.to: ['To', 'До'],
    LangText.meetingSatisfactionBetween: [
      'Meeting satisfaction between',
      'Зустріч задоволення між',
    ],
    LangText.and: ['and', 'і'],
    LangText.selectColumns: ['Select columns', 'Виберіть стовпці'],
    LangText.largeMeetings: ['Large meetings', 'Великі зустрічі'],
    LangText.cancelMultiUser: [
      'Cancel multi-select',
      'Скасувати багаторазовий вибір',
    ],
    LangText.multiSelect: ['Multi-select', 'Багаторазовий вибір'],
    LangText.showMultiSelectSummary: [
      'Show multi-select summary',
      'Показати підсумок із кількома виборами',
    ],
    LangText.createNewMeeting: ['Create new meeting', 'Створити нову зустріч'],
    LangText.amazing: ['Amazing', 'Дивовижний'],
    LangText.great: ['Great', 'Чудово'],
    LangText.ok: ['Ok', 'Ok'],
    LangText.inadequate: ['Inadequate', 'Неадекватна'],
    LangText.bad2: ['Bad', 'Погано'],
    LangText.preset: ['Preset', 'Попередньо встановлені'],
    LangText.presetNum: [
      'Number of people who selected the presets',
      'Кількість людей, які вибрали попередні налаштування',
    ],
    LangText.presets: [
      'Preset question manager',
      'Менеджер попередньо встановлених запитань',
    ],
    LangText.newPreset: ['New Preset', 'Новий пресет'],
    LangText.filters: ['Filters', 'фільтри'],
    LangText.generalQuality: [
      'In your opinion, what is the general quality of this meeting?',
      'Яка, на вашу думку, загальна якість цієї зустрічі?',
    ],
  };
}
